In [1]:
data_path = '../src/data/'

file_path = data_path + 'complete_microbiology_cultures_data.csv'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(file_path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474243 entries, 0 to 474242
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_proc_id_coded  474243 non-null  int64
 1   culture_description  474243 non-null  object
 2   antibiotic           474243 non-null  object
 3   age                  474243 non-null  object
 4   gender               474218 non-null  float64
 5   median_heartrate     473511 non-null  float64
 6   median_resprate      465406 non-null  float64
 7   median_temp          466756 non-null  float64
 8   median_sysbp         471344 non-null  float64
 9   median_diasbp        471148 non-null  float64
 10  median_wbc           465625 non-null  float64
 11  median_hgb           466581 non-null  float64
 12  median_plt           466098 non-null  float64
 13  median_na            465764 non-null  float64
 14  median_hco3          464870 non-null  float64
 15  median_bun           464324 non-null  float64
 16  median_cr            466943 non-null  float64
dtypes: float64(13), int64(1), object(3)
memory usage: 61.5+ MB

In [4]:
df.tail()

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
474238,606338977,URINE,Ciprofloxacin,35-44 years,0.0,77.0,16.0,97.9,126.0,84.0,9.6,13300.0,328.0,143.0,24.0,8.0,0.65
474239,523271451,URINE,Ciprofloxacin,75-84 years,0.0,79.0,16.0,98.5,149.0,73.0,NaN,13400.0,NaN,140.0,21.0,13.0,0.75
474240,510400314,BLOOD,Ciprofloxacin,25-34 years,0.0,96.0,18.0,98.2,97.0,77.0,7.1,7100.0,203.0,134.0,26.0,31.0,1.22
474241,437706157,URINE,Ciprofloxacin,above 90,0.0,98.0,18.0,98.0,156.0,75.0,6.0,11400.0,272.0,140.0,27.0,18.0,1.20
474242,780686388,URINE,Ampicillin/Sulbactam,above 90,0.0,62.0,18.0,97.1,109.0,53.0,6.8,10800.0,164.0,162.0,14.0,176.0,5.40

In [5]:
# check rows of order_proc_id_coded in (780686388, 510400314, 510400315)
lst = df[df['order_proc_id_coded'].isin([780686388, 437706157, 681936151])]
lst.shape

(73, 17)

In [6]:
lst.to_csv(data_path + 'filtered_cultures.csv', index=False)

In [7]:
lst[lst['order_proc_id_coded']==681936151]

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
4,681936151,URINE,Ertapenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
3388,681936151,URINE,Trimethoprim/Sulfamethoxazole,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
14913,681936151,URINE,Piperacillin/Tazobactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
18120,681936151,URINE,Gentamicin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
20576,681936151,URINE,Gentamicin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
23956,681936151,URINE,Ceftazidime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
45697,681936151,URINE,Ceftazidime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
110028,681936151,URINE,Cefepime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
112094,681936151,URINE,Ceftriaxone,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
144683,681936151,URINE,Amikacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
185071,681936151,URINE,Ceftriaxone,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
189074,681936151,URINE,Ampicillin/Sulbactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
241941,681936151,URINE,Ciprofloxacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
251986,681936151,URINE,Cefazolin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
257103,681936151,URINE,Amikacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
287421,681936151,URINE,Aztreonam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
302863,681936151,URINE,Ertapenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
314956,681936151,URINE,Aztreonam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
378173,681936151,URINE,Meropenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
382776,681936151,URINE,Nitrofurantoin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
429183,681936151,URINE,Piperacillin/Tazobactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
445487,681936151,URINE,Meropenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
447843,681936151,URINE,Ciprofloxacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
451650,681936151,URINE,Cefepime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
460349,681936151,URINE,Trimethoprim/Sulfamethoxazole,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77

In [8]:
df['age'].unique()

array(['75-84 years', '65-74 years', '55-64 years', '35-44 years',
       '45-54 years', 'above 90', '25-34 years', '85-89 years',
       '18-24 years'], dtype=object)

In [10]:
df[df['antibiotic']=='Colistin']

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
3638,438526036,RESPIRATORY,Colistin,25-34 years,1.0,99.0,18.0,98.2,122.0,63.0,8.5,11100.0,340.0,135.0,31.0,12.0,0.80
24246,357305056,RESPIRATORY,Colistin,25-34 years,0.0,94.0,18.0,97.0,92.0,44.0,10.6,9300.0,381.0,132.0,26.0,9.0,0.70
25251,432244315,RESPIRATORY,Colistin,35-44 years,0.0,112.0,20.0,94.3,93.0,64.0,23.3,7300.0,240.0,134.0,23.0,15.0,0.90
30947,339537616,RESPIRATORY,Colistin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.60
38175,387095511,RESPIRATORY,Colistin,25-34 years,0.0,96.0,19.0,97.3,108.0,64.0,12.5,11400.0,650.0,138.0,26.0,11.0,0.80
57398,330592991,RESPIRATORY,Colistin,45-54 years,0.0,78.0,13.0,97.0,109.0,63.0,6.4,11100.0,240.0,NaN,NaN,NaN,NaN
61837,362284980,RESPIRATORY,Colistin,25-34 years,0.0,95.0,20.0,97.3,104.0,59.0,14.8,11500.0,644.0,136.0,33.0,12.0,0.80
62893,339537616,RESPIRATORY,Colistin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.60
68016,397779317,RESPIRATORY,Colistin,45-54 years,1.0,51.0,20.0,98.4,148.0,88.0,14.4,14900.0,270.0,137.0,33.0,16.0,1.10
72192,446009052,RESPIRATORY,Colistin,18-24 years,0.0,119.0,35.0,98.2,124.0,80.0,15.2,9600.0,570.0,139.0,NaN,8.0,0.50
72716,442606608,RESPIRATORY,Colistin,25-34 years,0.0,112.0,18.0,98.4,134.0,83.0,7.8,7400.0,393.0,140.0,30.0,9.0,0.60
77537,366661583,RESPIRATORY,Colistin,25-34 years,0.0,104.0,18.0,97.0,116.0,76.0,12.4,12600.0,433.0,137.0,29.0,11.0,0.80
91754,380098744,RESPIRATORY,Colistin,35-44 years,0.0,88.0,18.0,98.4,114.0,69.0,7.2,12200.0,455.0,136.0,31.0,13.0,0.70
97309,803458012,URINE,Colistin,55-64 years,1.0,76.0,19.0,97.9,151.0,84.0,6.6,9200.0,346.0,133.0,24.0,12.0,1.35
97915,355333938,RESPIRATORY,Colistin,18-24 years,0.0,98.0,20.0,99.5,109.0,61.0,6.7,10300.0,361.0,134.0,25.0,6.0,0.80
105312,650121648,BLOOD,Colistin,55-64 years,1.0,104.0,14.0,101.4,97.0,68.0,10.7,12500.0,90.0,132.0,20.0,16.0,0.70
111876,402258737,RESPIRATORY,Colistin,25-34 years,1.0,85.0,18.0,97.3,103.0,67.0,6.7,12700.0,148.0,136.0,27.0,16.0,0.90
119600,450206472,RESPIRATORY,Colistin,18-24 years,0.0,101.0,31.0,98.2,98.0,54.0,12.7,7100.0,289.0,140.0,43.0,9.0,0.30
122803,402258737,RESPIRATORY,Colistin,25-34 years,1.0,85.0,18.0,97.3,103.0,67.0,6.7,12700.0,148.0,136.0,27.0,16.0,0.90
139735,326717958,RESPIRATORY,Colistin,18-24 years,0.0,140.0,20.0,98.1,132.0,85.0,16.1,10800.0,421.0,136.0,27.0,10.0,0.50
140400,473534592,RESPIRATORY,Colistin,35-44 years,0.0,88.0,20.0,97.9,139.0,79.0,15.5,12300.0,472.0,130.0,24.0,11.0,1.00
152105,355333938,RESPIRATORY,Colistin,18-24 years,0.0,98.0,20.0,99.5,109.0,61.0,6.7,10300.0,361.0,134.0,25.0,6.0,0.80
153151,429841593,RESPIRATORY,Colistin,35-44 years,0.0,80.0,18.0,98.3,120.0,75.0,11.6,12000.0,400.0,137.0,25.0,12.0,0.70
153325,473534592,RESPIRATORY,Colistin,35-44 years,0.0,88.0,20.0,97.9,139.0,79.0,15.5,12300.0,472.0,130.0,24.0,11.0,1.00
158047,349036554,RESPIRATORY,Colistin,18-24 years,0.0,127.0,20.0,97.7,119.0,81.0,17.4,10200.0,569.0,135.0,26.0,12.0,0.70
163877,753266770,URINE,Colistin,65-74 years,0.0,82.0,18.0,98.6,138.0,69.0,6.0,11800.0,174.0,143.0,24.0,24.0,0.85
171644,363750275,RESPIRATORY,Colistin,18-24 years,1.0,111.0,18.0,97.2,110.0,71.0,15.2,14000.0,448.0,139.0,27.0,5.0,0.80
188418,457916969,RESPIRATORY,Colistin,25-34 years,0.0,114.0,20.0,98.2,133.0,88.0,4.6,11000.0,132.0,131.0,29.0,12.0,0.70
189186,331559244,RESPIRATORY,Colistin,18-24 years,0.0,91.0,20.0,97.5,110.0,68.0,8.2,10800.0,245.0,138.0,22.0,16.0,1.20
220262,331559244,RESPIRATORY,Colistin,18-24 years,0.0,91.0,20.0,97.5,110.0,68.0,8.2,10800.0,245.0,138.0,22.0,16.0,1.20
221911,369689079,RESPIRATORY,Colistin,18-24 years,0.0,94.0,18.0,99.2,120.0,74.0,8.3,12600.0,210.0,141.0,29.0,9.0,0.70
234807,363980530,RESPIRATORY,Colistin,25-34 years,0.0,103.0,21.0,NaN,120.0,80.0,9.9,13300.0,368.0,138.0,30.0,14.0,0.90
244407,366661583,RESPIRATORY,Colistin,25-34 years,0.0,104.0,18.0,97.0,116.0,76.0,12.4,12600.0,433.0,137.0,29.0,11.0,0.80
251490,403796868,RESPIRATORY,Colistin,18-24 years,0.0,86.0,18.0,97.7,110.0,74.0,10.6,11100.0,222.0,132.0,24.0,14.0,0.90
252291,479002018,RESPIRATORY,Colistin,45-54 years,1.0,55.0,18.0,98.6,146.0,82.0,13.1,14500.0,349.0,132.0,27.0,16.0,1.10
268074,359928243,RESPIRATORY,Colistin,18-24 years,1.0,105.0,20.0,97.2,118.0,75.0,10.1,13400.0,400.0,137.0,32.0,12.0,0.90
273218,411399085,RESPIRATORY,Colistin,45-54 years,0.0,87.0,17.0,97.3,126.0,76.0,10.9,10000.0,319.0,136.0,30.0,19.0,0.80
277606,373788286,RESPIRATORY,Colistin,25-34 years,0.0,115.0,16.0,98.6,131.0,80.0,8.0,8200.0,291.0,136.0,18.0,27.0,2.00
281244,357305056,RESPIRATORY,Colistin,25-34 years,0.0,94.0,18.0,97.0,92.0,44.0,10.6,9300.0,381.0,132.0,26.0,9.0,0.70
285225,487976501,RESPIRATORY,Colistin,35-44 years,0.0,111.0,20.0,98.6,119.0,60.0,21.5,8000.0,616.0,133.0,27.0,16.0,0.80
287752,380098744,RESPIRATORY,Colistin,35-44 years,0.0,88.0,18.0,98.4,114.0,69.0,7.2,12200.0,455.0,136.0,31.0,13.0,0.70
293634,589638778,RESPIRATORY,Colistin,85-89 years,1.0,102.0,20.0,99.9,121.0,71.0,17.6,7500.0,288.0,134.0,25.0,42.0,1.17
298267,426098815,RESPIRATORY,Colistin,25-34 years,0.0,96.0,17.0,98.2,111.0,69.0,12.1,13300.0,335.0,138.0,26.0,16.0,0.80
299738,747951642,URINE,Colistin,55-64 years,0.0,94.0,20.0,99.1,142.0,75.0,8.9,11600.0,287.0,136.0,21.0,17.0,0.63
315559,445626440,RESPIRATORY,Colistin,18-24 years,1.0,102.0,22.0,97.7,116.0,75.0,18.6,10300.0,797.0,138.0,42.0,14.0,0.80
319603,363980530,RESPIRATORY,Colistin,25-34 years,0.0,103.0,21.0,NaN,120.0,80.0,9.9,13300.0,368.0,138.0,30.0,14.0,0.90
320275,430096843,RESPIRATORY,Colistin,25-34 years,0.0,110.0,22.0,98.1,137.0,82.0,7.8,7700.0,128.0,129.0,32.0,26.0,1.10
332356,369689079,RESPIRATORY,Colistin,18-24 years,0.0,94.0,18.0,99.2,120.0,74.0,8.3,12600.0,210.0,141.0,29.0,9.0,0.70
335694,349818069,RESPIRATORY,Colistin,35-44 years,0.0,85.0,20.0,97.0,115.0,78.0,7.5,13600.0,267.0,136.0,28.0,19.0,1.40
352488,430096843,RESPIRATORY,Colistin,25-34 years,0.0,110.0,22.0,98.1,137.0,82.0,7.8,7700.0,128.0,129.0,32.0,26.0,1.10
357434,396244771,BLOOD,Colistin,45-54 years,0.0,69.0,17.0,98.6,111.0,66.0,16.8,12300.0,126.0,137.0,25.0,13.0,1.00
368671,387095511,RESPIRATORY,Colistin,25-34 years,0.0,96.0,19.0,97.3,108.0,64.0,12.5,11400.0,650.0,138.0,26.0,11.0,0.80
415352,328399559,RESPIRATORY,Colistin,25-34 years,0.0,88.0,20.0,97.3,108.0,70.0,6.7,12000.0,345.0,134.0,27.0,15.0,0.80
415456,796236555,URINE,Colistin,75-84 years,0.0,73.0,20.0,98.7,125.0,52.0,14.2,9800.0,388.0,134.0,27.0,18.0,0.47
429567,415286187,RESPIRATORY,Colistin,25-34 years,0.0,87.0,16.0,97.7,104.0,69.0,7.0,11700.0,238.0,NaN,NaN,NaN,NaN
443849,445390423,RESPIRATORY,Colistin,25-34 years,0.0,112.0,20.0,97.9,141.0,92.0,10.0,8500.0,409.0,142.0,31.0,6.0,0.80
447967,362006368,URINE,Colistin,85-89 years,0.0,104.0,18.0,97.0,165.0,82.0,11.4,12100.0,263.0,138.0,26.0,22.0,1.30
456677,362284980,RESPIRATORY,Colistin,25-34 years,0.0,95.0,20.0,97.3,104.0,59.0,14.8,11500.0,644.0,136.0,33.0,12.0,0.80

In [12]:
ff = df[df['order_proc_id_coded']==339537616]

In [13]:
ff['antibiotic'].unique()

array(['Trimethoprim/Sulfamethoxazole', 'Colistin', 'Vancomycin',
       'Tobramycin', 'Linezolid', 'Piperacillin', 'Ceftazidime',
       'Aztreonam', 'Ticarcillin', 'Tetracycline', 'Imipenem',
       'Gentamicin', 'Amikacin'], dtype=object)

In [15]:
(df[df['order_proc_id_coded']==339537616])['antibiotic'].unique()

array(['Trimethoprim/Sulfamethoxazole', 'Colistin', 'Vancomycin',
       'Tobramycin', 'Linezolid', 'Piperacillin', 'Ceftazidime',
       'Aztreonam', 'Ticarcillin', 'Tetracycline', 'Imipenem',
       'Gentamicin', 'Amikacin'], dtype=object)

In [16]:
df[df['order_proc_id_coded']==339537616]

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
21772,339537616,RESPIRATORY,Trimethoprim/Sulfamethoxazole,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
30947,339537616,RESPIRATORY,Colistin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
62893,339537616,RESPIRATORY,Colistin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
99134,339537616,RESPIRATORY,Vancomycin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
104046,339537616,RESPIRATORY,Tobramycin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
136260,339537616,RESPIRATORY,Linezolid,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
149143,339537616,RESPIRATORY,Piperacillin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
161101,339537616,RESPIRATORY,Ceftazidime,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
171645,339537616,RESPIRATORY,Aztreonam,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
172802,339537616,RESPIRATORY,Ticarcillin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
204503,339537616,RESPIRATORY,Tobramycin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
213793,339537616,RESPIRATORY,Tetracycline,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
247978,339537616,RESPIRATORY,Imipenem,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
270629,339537616,RESPIRATORY,Gentamicin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6
352486,339537616,RESPIRATORY,Amikacin,18-24 years,1.0,125.0,33.0,98.4,124.0,80.0,7.0,12500.0,588.0,137.0,36.0,8.0,0.6