In [4]:
data_path = '../src/data/'

file_path = data_path + 'complete_microbiology_cultures_data.csv'

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(file_path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474243 entries, 0 to 474242
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_proc_id_coded  474243 non-null  int64
 1   culture_description  474243 non-null  object
 2   antibiotic           474243 non-null  object
 3   age                  474243 non-null  object
 4   gender               474218 non-null  float64
 5   median_heartrate     473511 non-null  float64
 6   median_resprate      465406 non-null  float64
 7   median_temp          466756 non-null  float64
 8   median_sysbp         471344 non-null  float64
 9   median_diasbp        471148 non-null  float64
 10  median_wbc           465625 non-null  float64
 11  median_hgb           466581 non-null  float64
 12  median_plt           466098 non-null  float64
 13  median_na            465764 non-null  float64
 14  median_hco3          464870 non-null  float64
 15  median_bun           464324 non-null  float64
 16  median_cr            466943 non-null  float64
dtypes: float64(13), int64(1), object(3)
memory usage: 61.5+ MB

In [16]:
df.tail()

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
474238,606338977,URINE,Ciprofloxacin,35-44 years,0.0,77.0,16.0,97.9,126.0,84.0,9.6,13300.0,328.0,143.0,24.0,8.0,0.65
474239,523271451,URINE,Ciprofloxacin,75-84 years,0.0,79.0,16.0,98.5,149.0,73.0,NaN,13400.0,NaN,140.0,21.0,13.0,0.75
474240,510400314,BLOOD,Ciprofloxacin,25-34 years,0.0,96.0,18.0,98.2,97.0,77.0,7.1,7100.0,203.0,134.0,26.0,31.0,1.22
474241,437706157,URINE,Ciprofloxacin,above 90,0.0,98.0,18.0,98.0,156.0,75.0,6.0,11400.0,272.0,140.0,27.0,18.0,1.20
474242,780686388,URINE,Ampicillin/Sulbactam,above 90,0.0,62.0,18.0,97.1,109.0,53.0,6.8,10800.0,164.0,162.0,14.0,176.0,5.40

In [17]:
# check rows of order_proc_id_coded in (780686388, 510400314, 510400315)
lst = df[df['order_proc_id_coded'].isin([780686388, 437706157, 681936151])]
lst.shape

(73, 17)

In [18]:
lst.to_csv(data_path + 'filtered_cultures.csv', index=False)

In [22]:
lst[lst['order_proc_id_coded']==681936151]

,order_proc_id_coded,culture_description,antibiotic,age,gender,median_heartrate,median_resprate,median_temp,median_sysbp,median_diasbp,median_wbc,median_hgb,median_plt,median_na,median_hco3,median_bun,median_cr
4,681936151,URINE,Ertapenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
3388,681936151,URINE,Trimethoprim/Sulfamethoxazole,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
14913,681936151,URINE,Piperacillin/Tazobactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
18120,681936151,URINE,Gentamicin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
20576,681936151,URINE,Gentamicin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
23956,681936151,URINE,Ceftazidime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
45697,681936151,URINE,Ceftazidime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
110028,681936151,URINE,Cefepime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
112094,681936151,URINE,Ceftriaxone,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
144683,681936151,URINE,Amikacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
185071,681936151,URINE,Ceftriaxone,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
189074,681936151,URINE,Ampicillin/Sulbactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
241941,681936151,URINE,Ciprofloxacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
251986,681936151,URINE,Cefazolin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
257103,681936151,URINE,Amikacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
287421,681936151,URINE,Aztreonam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
302863,681936151,URINE,Ertapenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
314956,681936151,URINE,Aztreonam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
378173,681936151,URINE,Meropenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
382776,681936151,URINE,Nitrofurantoin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
429183,681936151,URINE,Piperacillin/Tazobactam,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
445487,681936151,URINE,Meropenem,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
447843,681936151,URINE,Ciprofloxacin,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
451650,681936151,URINE,Cefepime,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77
460349,681936151,URINE,Trimethoprim/Sulfamethoxazole,65-74 years,0.0,91.0,19.0,98.3,145.0,86.0,8.1,12300.0,158.0,141.0,31.0,11.0,0.77